### ISSUE TITLE
setup auto builds for econ-ark-notebook docker image 

### ISSUE THREAD

**Issue by MridulS** [econ-ark/econ-ark-tools#4]

**Comment by MridulS** [comment]
Add option to take in requirements.txt from a PR

**Comment by llorracc** [comment]
@MridulS, 

There are still some circumstances in which it will be useful to have a full virtual machine version of the docker images:

1. It would be nice for the econ-ark team to have an always-available full VM version online so we can quickly try things out on a machine with a standard configuration different from that on our own machine, without worrying about.
1. It would also be better than asking students to install the VirtualBox VM.  It is valuable to have a full-fledged machine if you are actually editing, debugging, etc.  

So, this would basically mean installing a GUI as a last step.  I'd like to use the Xubuntu environment that is installed on my VirtualBox VM's.  

But this can be postponed until we have the base version of everything running properly.

**Comment by llorracc** [comment]
There's one more use case for an online VM:  For my class in Oslo, at least one student (I think maybe another one as well) basically has a computer so locked down that she can't install VirtualBox or Docker on it.  I'd like her to be able to do everything the other students are doing in the unix shell (I'm teaching them about git from the command line, forking repos, doing assignments on the fork, then posting their solutions as pull requests, etc).  Because I often teach courses to people from central banks or other government agencies, this is a situation that I've encountered before.  If we had a docker image that was a full VM, with GUI etc, I could have one or two students like this use that when all else fails.

**Comment by MridulS** [comment]
autobuild is up.
